DD_PRODUCT :=
DD_KERNEL :=
DD_KERNEL_BASE :=
DD_KERNEL_CMDLINE :=
DD_KERNEL_PAGESIZE :=
DD_DEVICE_CONFIG :=
DD_PRODUCT_ROOT :=
DD_BOOTRAMDISK_OFFSET :=
DD_DEVICE_SCREEN_TYPE :=
DD_RAMDISK_OFFSET :=
DD_TAGS_OFFSET :=
DD_DTIMG :=

