
ccflags-y += -I$(MTK_PATH_SOURCE)/../platform/mt6592/kernel/drivers/video \
		      -I$(MTK_PATH_SOURCE)/../platform/mt6592/kernel/drivers/dispsys

#obj-y += data_rgb888_64x64.o
obj-y += data_rgb888_64x64_golden.o
#obj-y += data_yuv420_3p_64x64_y.o
#obj-y += data_yuv420_3p_64x64_u.o
#obj-y += data_yuv420_3p_64x64_v.o
#obj-y += data_yuv420_3p_64x64_y_golden.o
#obj-y += data_yuv420_3p_64x64_u_golden.o
#obj-y += data_yuv420_3p_64x64_v_golden.o
#obj-y += data_yuv420_3p_64x64_golden.o
obj-y += data_argb_64x64.o
obj-y += data_argb_64x64_golden.o
#obj-y += data_uyvy_64x64.o
obj-y += data_rgb888_64x64_golden2.o