/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#include <platform/disp_drv_platform.h>

#include <platform/ufoe_reg.h>

#include <platform/sync_write.h>
#ifdef OUTREG32
  #undef OUTREG32
  #define OUTREG32(x, y) mt65xx_reg_sync_writel(y, x)
#endif

#ifndef OUTREGBIT
#define OUTREGBIT(TYPE,REG,bit,value)  \
                    do {    \
                        TYPE r = *((TYPE*)&INREG32(&REG));    \
                        r.bit = value;    \
                        OUTREG32(&REG, AS_UINT32(&r));    \
                    } while (0)
#endif

//////////////////////////////////////////////////////
UFOE_REGS regBackup;
static bool s_isUfoePowerOn = FALSE;
static PUFOE_REGS const UFOE_REG = (PUFOE_REGS)(DISP_UFOE_BASE + 0x800);

static long int get_current_time_us(void)
{
	return 0;
}

static void _ResetBackupedUFOERegisterValues(void)
{
    UFOE_REGS *regs = &regBackup;
    memset((void*)regs, 0, sizeof(UFOE_REGS));
}

void UFOE_DumpRegisters(void)
{
	unsigned int i = 0;
	for (i = 0; i < 32; i += 16)
	{
		printk("UFOE+%04x : 0x%08x   0x%08x  0x%08x  0x%08x\n", i, INREG32((DISP_UFOE_BASE + 0x800+i)), INREG32((DISP_UFOE_BASE + 0x800+i+0x4)), INREG32((DISP_UFOE_BASE + 0x800+i+0x8)), INREG32((DISP_UFOE_BASE + 0x800+i+0xc)));
	}
	for (i = 0x700; i < 0x700 + 96; i += 16)
	{
		printk("UFOE+%04x : 0x%08x   0x%08x  0x%08x  0x%08x\n", i+0x800, INREG32((DISP_UFOE_BASE + 0x800+i)), INREG32((DISP_UFOE_BASE + 0x800+i+0x4)), INREG32((DISP_UFOE_BASE + 0x800+i+0x8)), INREG32((DISP_UFOE_BASE + 0x800+i+0xc)));
	}
}

void UFOE_BackupRegisters(void)
{
    UFOE_REGS *regs = &regBackup;

    DISP_OUTREG32_R(UINT32*, &regs->UFOE_CFG_0B, &UFOE_REG->UFOE_CFG_0B);
    DISP_OUTREG32_R(UINT32*, &regs->UFOE_CFG_1B, &UFOE_REG->UFOE_CFG_1B);
    DISP_OUTREG32_R(UINT32*, &regs->UFOE_FRA_WIDTH, &UFOE_REG->UFOE_FRA_WIDTH);
    DISP_OUTREG32_R(UINT32*, &regs->UFOE_FRA_HEIGHT, &UFOE_REG->UFOE_FRA_HEIGHT);
	DISP_OUTREG32_R(PUFOE_INTEN_REG, &regs->UFOE_INTEN, &UFOE_REG->UFOE_INTEN);

	regs->UFOE_START.ufoe_bypass = UFOE_REG->UFOE_START.ufoe_bypass;

	DISP_OUTREG32_R(UINT32*, &regs->UFOE_DBUF, &UFOE_REG->UFOE_DBUF);
	DISP_OUTREG32_R(PUFOE_CRC_REG, &regs->UFOE_CRC, &UFOE_REG->UFOE_CRC);
	DISP_OUTREG32_R(UINT32*, &regs->UFOE_SW_SCRATCH, &UFOE_REG->UFOE_SW_SCRATCH);
	DISP_OUTREG32_R(UINT32*, &regs->UFOE_CK_ON, &UFOE_REG->UFOE_CK_ON);
	DISP_OUTREG32_R(PUFOE_R0_CRC_REG, &regs->UFOE_R0_CRC, &UFOE_REG->UFOE_R0_CRC);
}


void UFOE_RestoreRegisters(void)
{
    UFOE_REGS *regs = &regBackup;

    DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_CFG_0B, &regs->UFOE_CFG_0B);
    DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_CFG_1B, &regs->UFOE_CFG_1B);
    DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_FRA_WIDTH, &regs->UFOE_FRA_WIDTH);
    DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_FRA_HEIGHT, &regs->UFOE_FRA_HEIGHT);

    DISP_OUTREG32_R(PUFOE_INTEN_REG, &UFOE_REG->UFOE_INTEN, &regs->UFOE_INTEN);

	UFOE_REG->UFOE_START.ufoe_bypass = regs->UFOE_START.ufoe_bypass;

	DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_DBUF, &regs->UFOE_DBUF);
	DISP_OUTREG32_R(PUFOE_CRC_REG, &UFOE_REG->UFOE_CRC, &regs->UFOE_CRC);
	DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_SW_SCRATCH, &regs->UFOE_SW_SCRATCH);
	DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_CK_ON, &regs->UFOE_CK_ON);
	DISP_OUTREG32_R(PUFOE_R0_CRC_REG, &UFOE_REG->UFOE_R0_CRC, &regs->UFOE_R0_CRC);
}

void UFOE_PowerOn(void)
{
		if (!s_isUfoePowerOn)
    {
        MASKREG32(0x14000108, 0x100000, 0x100000);
		printf("\n[DISP] - UFOE_PowerOn. 0x%8x\n", INREG32(0x14000100));
        s_isUfoePowerOn = TRUE;
//		UFOE_RestoreRegisters();
    }
}

void UFOE_PowerOff(void)
{
		if (s_isUfoePowerOn)
    {
        MASKREG32(0x14000104, 0x100000, 0x100000);
		printf("\n[DISP] - UFOE_PowerOFF. 0x%8x\n", INREG32(0x14000100));
        s_isUfoePowerOn = FALSE;
    }
}

void UFOE_Init(BOOL isUFOEPoweredOn)
{
    if (isUFOEPoweredOn) {
        UFOE_BackupRegisters();
    } else {
        _ResetBackupedUFOERegisterValues();
    }
	UFOE_PowerOn();
    DISP_OUTREGBIT(UFOE_INTEN_REG, UFOE_REG->UFOE_INTEN, ufoe_fra_underrun, 1);
    DISP_OUTREGBIT(UFOE_INTEN_REG, UFOE_REG->UFOE_INTEN, ufoe_fra_done, 1);
    DISP_OUTREGBIT(UFOE_INTEN_REG, UFOE_REG->UFOE_INTEN, ufoe_fra_complete, 1);
//	UFOE_REG->UFOE_CK_ON = 0x1;
}

void UFOE_Config(UFOE_para ufoe_config)
{
    DISP_OUTREGBIT(UFOE_START_REG, UFOE_REG->UFOE_START, ufoe_bypass, ufoe_config.bypass);
    DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_CFG_0B, &ufoe_config.ufoe_cfg_0);
    DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_CFG_1B, &ufoe_config.ufoe_cfg_1);
	DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_FRA_WIDTH, &ufoe_config.width);
    DISP_OUTREG32_R(UINT32*, &UFOE_REG->UFOE_FRA_HEIGHT, &ufoe_config.height);
	
	UFOE_DumpRegisters();
}

void UFOE_Start(void)
{
    DISP_OUTREGBIT(UFOE_START_REG, UFOE_REG->UFOE_START, ufoe_start, 0);
    DISP_OUTREGBIT(UFOE_START_REG, UFOE_REG->UFOE_START, ufoe_start, 1);
}
