#ifndef _STATUS_H_
#define _STATUS_H_

typedef enum {

    S_DONE = 0
    ,S_UNDEFINED_ERROR
    ,S_INVALID_ARGUMENTS
	,S_TIMEOUT
	,S_STOP
	,S_COM_PORT_OPEN_FAIL
    ,S_COM_PORT_SET_TIMEOUT_FAIL
    ,S_COM_PORT_SET_STATE_FAIL
    ,S_COM_PORT_PURGE_FAIL
	   //For Preloader command
    ,S_PL_MODE_UNSUPPORTED = 10001
    ,S_PL_MODE_FORBIDDEN
    ,S_PL_MODE_INVALID_ARGUMETS
    ,S_PL_READ_FAIL
    ,S_PL_WRITE_FAIL
    ,S_PL_READ_TIMEOUT
    ,S_PL_WRITE_TIMEOUT
};


#endif