#include "../cfgfileinc/CFG_Custom1_File.h"
#include "../cfgfileinc/CFG_Salesregflag_File.h"
#include "../cfgfileinc/CFG_PRODUCT_INFO_File.h"
#include "../cfgfileinc/CFG_GPS_File.h"
#include "../cfgfileinc/CFG_Model_File.h"
#include "../cfgfileinc/CFG_Psensor_File.h"
#include "../cfgfileinc/CFG_Wifi_File.h"
