/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Apr 03 14:11:03 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


