LOCAL_PATH := $(call my-dir)
include $(DD_CLEAR)
DD_PRODUCT := n880e
DD_KERNEL := $(LOCAL_PATH)/kernel

DD_KERNEL_BASE := 0x200000
DD_KERNEL_PAGESIZE := 4096
DD_KERNEL_CMDLINE := androidboot.hardware=atlas40
DD_DEVICE_SCREEN_TYPE := "HDPI"

DD_PRODUCT_ROOT := $(LOCAL_PATH)/root
DD_DEVICE_CONFIG := $(LOCAL_PATH)/*.conf
include $(DD_RECOVERY)
