/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 17 13:20:54 2014
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1




#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_CNT      0


