/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 17 13:20:54 2014
 * Do Not Modify the File.
 */









/**********Output default name********************/

#define PMIC_APP_Camera_A         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Camera_A2         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Camera_D         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Camera_D2         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_G_sensor         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_M_3G_PA         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_M_sensor         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Cap_touch         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Cyroscope         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_WiFi2V8         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_WiFi1V8         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Bluetooth         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_FM_Radio         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_BFC         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_OFN         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Vibrator         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Memory_Card         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_SIM2         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_mATV         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_CMMB         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_eMMC         MT6322_POWER_LDO_DEFAULT

#define PMIC_APP_Others         MT6322_POWER_LDO_DEFAULT






