/*
 * This file is generated automatically according to the design of silicon.
 * Don't modify it directly.
 */

X_DEFINE_IRQ(MCU_XGPT0_IRQ_ID              , 88,  H, LEVEL)
X_DEFINE_IRQ(MCU_XGPT1_IRQ_ID              , 89,  H, LEVEL)
X_DEFINE_IRQ(MCU_XGPT2_IRQ_ID              , 90,  H, LEVEL)
X_DEFINE_IRQ(MCU_XGPT3_IRQ_ID              , 91,  H, LEVEL)
X_DEFINE_IRQ(MCU_XGPT4_IRQ_ID              , 92,  H, LEVEL)
X_DEFINE_IRQ(MCU_XGPT5_IRQ_ID              , 93,  H, LEVEL)
X_DEFINE_IRQ(MCU_XGPT6_IRQ_ID              , 94,  H, LEVEL)
X_DEFINE_IRQ(MCU_XGPT7_IRQ_ID              , 95,  H, LEVEL)
X_DEFINE_IRQ(MT_USB0_IRQ_ID                , 96,  L, LEVEL)
//X_DEFINE_IRQ(MT_USB1_IRQ_ID                , 97,  L, LEVEL)
X_DEFINE_IRQ(TS_IRQ_ID                     , 98,  L, EDGE)
X_DEFINE_IRQ(TS_BATCH_IRQ_ID               , 99,  L, EDGE)
X_DEFINE_IRQ(LOWBATTERY_IRQ_ID             , 100,  L, EDGE)
X_DEFINE_IRQ(PWM_IRQ_ID                    , 101,  L, LEVEL)
X_DEFINE_IRQ(THERM_CTRL_IRQ_ID             , 102,  L, LEVEL)
X_DEFINE_IRQ(MT_MSDC0_IRQ_ID               , 103,  L, LEVEL)
X_DEFINE_IRQ(MT_MSDC1_IRQ_ID               , 104,  L, LEVEL)
X_DEFINE_IRQ(MSDC2_IRQ_ID                  , 105,  L, LEVEL)
X_DEFINE_IRQ(MT_I2C0_IRQ_ID                , 108,  L, LEVEL)
X_DEFINE_IRQ(MT_I2C1_IRQ_ID                , 109,  L, LEVEL)
X_DEFINE_IRQ(MT_I2C2_IRQ_ID                , 110,  L, LEVEL)
X_DEFINE_IRQ(BTIF_IRQ_ID                   , 114,  L, LEVEL)
X_DEFINE_IRQ(MT_UART1_IRQ_ID               , 115,  L, LEVEL)
X_DEFINE_IRQ(MT_UART2_IRQ_ID               , 116,  L, LEVEL)
X_DEFINE_IRQ(MT_UART3_IRQ_ID               , 117,  L, LEVEL)
X_DEFINE_IRQ(MT_UART4_IRQ_ID               , 118,  L, LEVEL)
X_DEFINE_IRQ(NFIECC_IRQ_ID                 , 119,  L, LEVEL)
X_DEFINE_IRQ(NFI_IRQ_ID                    , 120,  L, LEVEL)
X_DEFINE_IRQ(MT_GDMA1_IRQ_ID               , 121,  L, LEVEL)
X_DEFINE_IRQ(MT_GDMA2_IRQ_ID               , 122,  L, LEVEL)
X_DEFINE_IRQ(MT6582_HIF_PDMA_IRQ_ID        , 123,  L, LEVEL)
X_DEFINE_IRQ(AP_DMA_I2C0_IRQ_ID            , 124,  L, LEVEL)
X_DEFINE_IRQ(AP_DMA_I2C1_IRQ_ID            , 125,  L, LEVEL)
X_DEFINE_IRQ(AP_DMA_I2C2_IRQ_ID            , 126,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART0_TX_IRQ_ID        , 127,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART0_RX_IRQ_ID        , 128,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART1_TX_IRQ_ID        , 129,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART1_RX_IRQ_ID        , 130,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART2_TX_IRQ_ID        , 131,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART2_RX_IRQ_ID        , 132,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART3_TX_IRQ_ID        , 133,  L, LEVEL)
X_DEFINE_IRQ(MT_DMA_UART3_RX_IRQ_ID        , 134,  L, LEVEL)
X_DEFINE_IRQ(AP_DMA_BTIF_TX_IRQ_ID         , 135,  L, LEVEL)
X_DEFINE_IRQ(AP_DMA_BTIF_RX_IRQ_ID         , 136,  L, LEVEL)
X_DEFINE_IRQ(MT_SPI1_IRQ_ID            , 142,  L, LEVEL)  // modified in 82M
//X_DEFINE_IRQ(MSDC0_WAKEUP_PS_IRQ_ID        , 143,  H, EDGE)
//X_DEFINE_IRQ(MSDC1_WAKEUP_PS_IRQ_ID        , 144,  H, EDGE)
//X_DEFINE_IRQ(MSDC2_WAKEUP_PS_IRQ_ID        , 145,  H, EDGE)
X_DEFINE_IRQ(MT_PTP_FSM_IRQ_ID             , 149,  L, LEVEL)
//X_DEFINE_IRQ(BTIF_WAKEUP_IRQ_ID            , 150,  L, LEVEL)
X_DEFINE_IRQ(MT_WDT_IRQ_ID                 , 152,  L, EDGE)
X_DEFINE_IRQ(DCC_APARM_IRQ_ID              , 156,  L, LEVEL)
//X_DEFINE_IRQ(APARM_CTI_IRQ_ID              , 157,  L, LEVEL)
X_DEFINE_IRQ(MT_APARM_DOMAIN_IRQ_ID        , 158,  L, LEVEL)
X_DEFINE_IRQ(MT_APARM_DECERR_IRQ_ID        , 159,  L, LEVEL)
X_DEFINE_IRQ(DOMAIN_ABORT_IRQ_ID0          , 160,  L, LEVEL)
X_DEFINE_IRQ(BUS_DBG_TRACKER_IRQ_ID0       , 161,  L, LEVEL) // new in 82M
X_DEFINE_IRQ(CCIF0_AP_IRQ_ID               , 164,  L, LEVEL)
X_DEFINE_IRQ(AFE_MCU_IRQ_ID                , 168,  L, LEVEL)
X_DEFINE_IRQ(M4U1_IRQ_ID                   , 170,  L, LEVEL)
X_DEFINE_IRQ(M4UL2_IRQ_ID                  , 171,  L, LEVEL)
X_DEFINE_IRQ(M4UL2_SEC_IRQ_ID              , 172,  L, LEVEL)
X_DEFINE_IRQ(REFRESH_RATE_IRQ_ID           , 173,  L, EDGE)
X_DEFINE_IRQ(MT6592_APARM_GPTTIMER_IRQ_LINE, 176,  L, LEVEL)
X_DEFINE_IRQ(MT_EINT_IRQ_ID                , 177,  H, LEVEL)
X_DEFINE_IRQ(EINT_EVENT_IRQ_ID             , 178,  L, LEVEL)

X_DEFINE_IRQ(MT_EINT_DIRECT0_IRQ_ID        , 179,  H, LEVEL)  // change vector in 82M
X_DEFINE_IRQ(MT_EINT_DIRECT1_IRQ_ID        , 180,  H, LEVEL)  // change vector in 82M
X_DEFINE_IRQ(MT_EINT_DIRECT2_IRQ_ID        , 181,  H, LEVEL)  // change vector in 82M
X_DEFINE_IRQ(MT_EINT_DIRECT3_IRQ_ID        , 182,  H, LEVEL)  // change vector in 82M
X_DEFINE_IRQ(MT_EINT_DIRECT4_IRQ_ID        , 183,  H, LEVEL)  // change vector in 82M
X_DEFINE_IRQ(MT_EINT_DIRECT5_IRQ_ID        , 184,  H, LEVEL)  // change vector in 82M
X_DEFINE_IRQ(MT_EINT_DIRECT6_IRQ_ID        , 185,  H, LEVEL)  // change vector in 82M
X_DEFINE_IRQ(MT_EINT_DIRECT7_IRQ_ID        , 186,  H, LEVEL)  // change vector in 82M

X_DEFINE_IRQ(MT_PMIC_WRAP_IRQ_ID       , 187,  H, LEVEL)
X_DEFINE_IRQ(MT_KP_IRQ_ID                  , 188,  L, EDGE)
X_DEFINE_IRQ(MT_SPM_IRQ_ID                 , 189,  L, LEVEL)
X_DEFINE_IRQ(MT_SPM1_IRQ_ID                , 190,  L, LEVEL)
X_DEFINE_IRQ(MT_SPM2_IRQ_ID                , 191,  L, LEVEL)
X_DEFINE_IRQ(MT_SPM3_IRQ_ID                , 192,  L, LEVEL)
X_DEFINE_IRQ(MT_SPM4_IRQ_ID                , 193,  L, LEVEL)  // new in 82M
X_DEFINE_IRQ(MT_SPM5_IRQ_ID                , 194,  L, LEVEL)  // new in 82M
X_DEFINE_IRQ(MT_SPM6_IRQ_ID                , 195,  L, LEVEL)  // new in 82M
X_DEFINE_IRQ(MT_SPM7_IRQ_ID                , 196,  L, LEVEL)  // new in 82M
//X_DEFINE_IRQ(MT_EINT_DIRECT0_IRQ_ID        , 185,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT1_IRQ_ID        , 186,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT2_IRQ_ID        , 187,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT3_IRQ_ID        , 188,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT4_IRQ_ID        , 189,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT5_IRQ_ID        , 190,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT6_IRQ_ID        , 191,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT7_IRQ_ID        , 192,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT8_IRQ_ID        , 193,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT9_IRQ_ID        , 194,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT10_IRQ_ID       , 195,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT11_IRQ_ID       , 196,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT12_IRQ_ID       , 197,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT13_IRQ_ID       , 198,  H, LEVEL)
//X_DEFINE_IRQ(MT_EINT_DIRECT14_IRQ_ID       , 199,  H, LEVEL)
X_DEFINE_IRQ(SMI_LARB0_IRQ_ID              , 200,  L, LEVEL)
X_DEFINE_IRQ(SMI_LARB1_IRQ_ID              , 201,  L, LEVEL)
X_DEFINE_IRQ(SMI_LARB2_IRQ_ID              , 202,  L, LEVEL)
X_DEFINE_IRQ(MT_VDEC_IRQ_ID                , 203,  L, LEVEL)
X_DEFINE_IRQ(MT_VENC_IRQ_ID                , 204,  L, LEVEL)
X_DEFINE_IRQ(MT6582_JPEG_ENC_IRQ_ID        , 205,  L, LEVEL)
X_DEFINE_IRQ(SENINF_IRQ_ID                 , 206,  L, LEVEL)
X_DEFINE_IRQ(CAMERA_ISP_IRQ0_ID            , 207,  L, LEVEL)
X_DEFINE_IRQ(CAMERA_ISP_IRQ1_ID            , 208,  L, LEVEL)
X_DEFINE_IRQ(CAMERA_ISP_IRQ2_ID            , 209,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_MDP_RDMA_IRQ_ID   , 210,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_MDP_RSZ0_IRQ_ID   , 211,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_MDP_RSZ1_IRQ_ID   , 212,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_MDP_TDSHP_IRQ_ID  , 213,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_MDP_WDMA_IRQ_ID   , 214,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_MDP_WROT_IRQ_ID   , 215,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_RDMA_IRQ_ID       , 216,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_OVL_IRQ_ID        , 217,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_WDMA_IRQ_ID       , 218,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_BLS_IRQ_ID        , 219,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_COLOR_IRQ_ID      , 220,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_DSI_IRQ_ID        , 221,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_DPI0_IRQ_ID       , 222,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_CMDQ_IRQ_ID       , 223,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_CMDQ_SECURE_IRQ_ID, 224,  L, LEVEL)
X_DEFINE_IRQ(MT_DISP_MUTEX_IRQ_ID      , 225,  L, LEVEL)

X_DEFINE_IRQ(MM_DUMMY0_IRQ_ID              , 226,  L, LEVEL)
X_DEFINE_IRQ(DISP_RDMA1_IRQ_ID             , 227,  L, LEVEL) // new in 82M
X_DEFINE_IRQ(DISP_UFOE_IRQ_ID              , 228,  L, LEVEL) // new in 82M
X_DEFINE_IRQ(MM_DUMMY1_IRQ_ID              , 229,  L, LEVEL) // change index in 82M
X_DEFINE_IRQ(MM_DUMMY2_IRQ_ID              , 230,  L, LEVEL) // change index in 82M
X_DEFINE_IRQ(MM_DUMMY3_IRQ_ID              , 231,  L, LEVEL) // change index in 82M
X_DEFINE_IRQ(MJC_SMI_LARB_IRQ_ID           , 232,  L, LEVEL) // new in 82M
X_DEFINE_IRQ(MJC_TOP_IRQ_ID                , 233,  L, LEVEL) // new in 82M

//X_DEFINE_IRQ(MT_MFG_IRQ_GP_ID              , 234,  L, LEVEL) // rename to index type
//X_DEFINE_IRQ(MT_MFG_IRQ_GPMMU_ID           , 235,  L, LEVEL)
//X_DEFINE_IRQ(MT_MFG_IRQ_PP0_ID             , 236,  L, LEVEL)
//X_DEFINE_IRQ(MT_MFG_IRQ_PPMMU0_ID          , 237,  L, LEVEL)
//X_DEFINE_IRQ(MT_MFG_IRQ_PP1_ID             , 238,  L, LEVEL)
//X_DEFINE_IRQ(MT_MFG_IRQ_PPMMU1_ID          , 239,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ0_ID                , 234,  L, LEVEL) // new naming in 82M
X_DEFINE_IRQ(MT_MFG_IRQ1_ID                , 235,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ2_ID                , 236,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ3_ID                , 237,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ4_ID                , 238,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ5_ID                , 239,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ6_ID                , 240,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ7_ID                , 241,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ8_ID                , 242,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ9_ID                , 243,  L, LEVEL)
X_DEFINE_IRQ(MT_MFG_IRQ10_ID               , 244,  L, LEVEL)

X_DEFINE_IRQ(MD_WDT_IRQ_ID                 , 245,  L, EDGE)

X_DEFINE_IRQ(CONN_WDT_IRQ_ID               , 249,  L, EDGE)  // change index
X_DEFINE_IRQ(WF_HIF_IRQ_ID                 , 250,  L, LEVEL)  // change index
X_DEFINE_IRQ(MT_CONN2AP_BTIF_WAKEUP_IRQ_ID , 251,  L, LEVEL)  // change index
X_DEFINE_IRQ(BT_CVSD_IRQ_ID                , 252,  L, LEVEL)  // change index
X_DEFINE_IRQ(MT_CIRQ_IRQ_ID                , 253,  L, LEVEL)  // change index
