
# Makefile for the power golden setting.
#

obj-y += mt_power_gs.o
obj-y += mt_power_gs_cg_array.o
obj-y += mt_power_gs_dcm_array.o
obj-y += mt_power_gs_chg_buck_array.o
obj-y += mt_power_gs_ldo_buck_array.o
obj-y += mt_power_gs_suspend.o
obj-y += mt_power_gs_dpidle.o
obj-y += mt_power_gs_idle.o
obj-y += mt_power_gs_audio_playback.o
