// This file is generated by GenLP_setting.pl v1.4

#include <linux/init.h>
#include <linux/module.h>
#include <linux/kernel.h>

#include <mach/mt_typedefs.h>
#include <mach/mt_power_gs.h>

const unsigned int CHG33_CHG_BUCK_gs_dpidle_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0004 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_dpidle = CHG33_CHG_BUCK_gs_dpidle_data;

unsigned int CHG33_CHG_BUCK_gs_dpidle_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_suspend_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0000 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_suspend = CHG33_CHG_BUCK_gs_suspend_data;

unsigned int CHG33_CHG_BUCK_gs_suspend_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_vp_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0003 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_vp = CHG33_CHG_BUCK_gs_vp_data;

unsigned int CHG33_CHG_BUCK_gs_vp_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_paging_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0003 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_paging = CHG33_CHG_BUCK_gs_paging_data;

unsigned int CHG33_CHG_BUCK_gs_paging_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_mp3_play_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0004 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_mp3_play = CHG33_CHG_BUCK_gs_mp3_play_data;

unsigned int CHG33_CHG_BUCK_gs_mp3_play_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_idle_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0003 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_idle = CHG33_CHG_BUCK_gs_idle_data;

unsigned int CHG33_CHG_BUCK_gs_idle_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_talk_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0003 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_talk = CHG33_CHG_BUCK_gs_talk_data;

unsigned int CHG33_CHG_BUCK_gs_talk_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_connsys_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0003 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_connsys = CHG33_CHG_BUCK_gs_connsys_data;

unsigned int CHG33_CHG_BUCK_gs_connsys_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_datalink_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0003 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_datalink = CHG33_CHG_BUCK_gs_datalink_data;

unsigned int CHG33_CHG_BUCK_gs_datalink_len = 9;

const unsigned int CHG33_CHG_BUCK_gs_vr_data[] = {
 // Address     Mask        Golden Setting Value
    0x006D, 0x007F, 0x0000,// VCORE_CON22
    0x009F, 0x0080, 0x0000,// VRF18_CON21
    0x00A0, 0x0007, 0x0003 // VRF18_CON22
};

const unsigned int *CHG33_CHG_BUCK_gs_vr = CHG33_CHG_BUCK_gs_vr_data;

unsigned int CHG33_CHG_BUCK_gs_vr_len = 9;

