/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Apr 17 22:55:57 2013
 * Do Not Modify the File.
 */



#include <mach/upmu_sw.h>


//****for customer use*******// 


//PMIC default enable/disable result

//PMIC mode select 
typedef enum
{
   BY_ENABLE = 0,
   BY_SRCLKEN = 1
}MODE_sel_enum;

////For Common use 

//For PMIC driver use




