/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Tue Apr 23 17:40:49 2013
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_BPI     GPIO_VIO18
#define GPIO_DVDD28_BSI     GPIO_VIO18
#define GPIO_DVDD28_NML2     GPIO_VIO28
#define MSDC_POWER_MC1     MSDC_VMC
#define MSDC_POWER_MC2     MSDC_VIO18_MC2
#define MUSB_POWER_PORT1     MUSB_VUSB33


