// Auto generated. Import ProjectConfig.mk
#define CUSTOM_SUSBDL_CFG ATTR_SUSBDL_ONLY_ENABLE_ON_SCHIP
#define CUSTOM_SBOOT_CFG ATTR_SBOOT_ONLY_ENABLE_ON_SCHIP
#define MTK_SEC_MODEM_AUTH no
#define MTK_SEC_SECRO_AC_SUPPORT yes
