/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Thu Apr 18 11:18:15 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


